trigger:
  - databasefix

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: PackageSource
        steps:
          - checkout: self

          # Copy only the necessary source files to staging folder
          - script: |
              mkdir app_package
              rsync -av --progress ./ app_package \
                --exclude .git \
                --exclude .gitignore \
                --exclude .github \
                --exclude .azure-pipelines \
                --exclude '*.env' \
                --exclude 'node_modules' \
                --exclude 'venv' \
                --exclude '__pycache__' \
                --exclude '*.pyc' \
                --exclude '*.log' \
                --exclude '*.sqlite3'
            displayName: "Prepare clean package"

          # Publish only the clean package as artifact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'app_package'
              ArtifactName: 'drop'
              publishLocation: 'Container'
