# Pydantic schemas for request/response models

from .response import (
    BaseResponse,
    SuccessResponse,
    ErrorResponse,
    PaginationInfo,
    PaginatedResponse,
    MessageResponse,
    AuthResponse,
    TokenResponse,
    UserResponse,
    ContentResponse,
    GenreResponse,
    StreamingResponse,
    AdminResponse,
    GenreListResponse,
    ContentListResponse,
    UserListResponse,
    StreamingListResponse,
    GenreWithMoviesListResponse,
    AdCampaignListResponse,
    UserAdminListResponse,
    ProfileResponse,
    SearchHistoryResponse,
    ReviewResponse,
    CastCrewResponse,
    PerformanceResponse,
    MonetizationResponse,
)
from .continue_watching import (
    WatchProgressUpdate,
    WatchProgressResponse,
    ContinueWatchingItem,
    ContinueWatchingResponse,
    ResumePositionResponse,
    WatchProgressStats,
    MarkAsCompletedRequest,
    RemoveFromContinueWatchingRequest,
)
from .recently_watched import (
    RecentlyWatchedItem,
    RecentlyWatchedResponse,
    RecentlyWatchedStats,
    RecentlyWatchedDetail,
)

__all__ = [
    "BaseResponse",
    "SuccessResponse", 
    "ErrorResponse",
    "PaginationInfo",
    "PaginatedResponse",
    "MessageResponse",
    "AuthResponse",
    "TokenResponse",
    "UserResponse",
    "ContentResponse",
    "GenreResponse",
    "StreamingResponse",
    "AdminResponse",
    "GenreListResponse",
    "ContentListResponse",
    "UserListResponse",
    "StreamingListResponse",
    "GenreWithMoviesListResponse",
    "AdCampaignListResponse",
    "UserAdminListResponse",
    "ProfileResponse",
    "SearchHistoryResponse",
    "ReviewResponse",
    "CastCrewResponse",
    "PerformanceResponse",
    "MonetizationResponse",
    # Watch Progress schemas
    "WatchProgressUpdate",
    "WatchProgressResponse",
    "ContinueWatchingItem",
    "ContinueWatchingResponse",
    "ResumePositionResponse",
    "WatchProgressStats",
    "MarkAsCompletedRequest",
    "RemoveFromContinueWatchingRequest",
    # Recently Watched schemas
    "RecentlyWatchedItem",
    "RecentlyWatchedResponse",
    "RecentlyWatchedStats",
    "RecentlyWatchedDetail",
]