"""add_unique_constraint_to_faq_question

Revision ID: 0996c802007f
Revises: 89be161b4482
Create Date: 2025-11-13 16:05:33.286056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0996c802007f'
down_revision = '89be161b4482'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, remove duplicate FAQs (keep the most recent one for each question)
    connection = op.get_bind()
    
    # Delete duplicates, keeping only the most recent one for each question
    connection.execute(sa.text("""
        DELETE FROM faqs
        WHERE id NOT IN (
            SELECT DISTINCT ON (question) id
            FROM faqs
            WHERE is_deleted = false
            ORDER BY question, created_at DESC
        )
        AND is_deleted = false
    """))
    
    op.drop_index(op.f('ix_faqs_question'), table_name='faqs')
    op.create_index(op.f('ix_faqs_question'), 'faqs', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faqs_question'), table_name='faqs')
    op.create_index(op.f('ix_faqs_question'), 'faqs', ['question'], unique=False)
    # ### end Alembic commands ###
