"""Update streaming channels with category enum

Revision ID: 0cbc8661522b
Revises: 5089981dcce0
Create Date: 2025-09-24 01:56:10.726675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbc8661522b'
down_revision = '5089981dcce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    streaming_channel_category_enum = sa.Enum('NEWS', 'SPORTS', 'ENTERTAINMENT', 'RELIGIOUS', 'KIDS', 'DOCUMENTARY', 'MOVIES', 'MUSIC', 'EDUCATIONAL', 'LIFESTYLE', name='streamingchannelcategory')
    streaming_channel_category_enum.create(op.get_bind())

    # Alter the column to use the enum
    op.alter_column('streaming_channels', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=streaming_channel_category_enum,
               existing_nullable=True,
               postgresql_using='category::streamingchannelcategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter the column back to VARCHAR
    op.alter_column('streaming_channels', 'category',
               existing_type=sa.Enum('NEWS', 'SPORTS', 'ENTERTAINMENT', 'RELIGIOUS', 'KIDS', 'DOCUMENTARY', 'MOVIES', 'MUSIC', 'EDUCATIONAL', 'LIFESTYLE', name='streamingchannelcategory'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               postgresql_using='category::varchar')

    # Drop the enum type
    sa.Enum(name='streamingchannelcategory').drop(op.get_bind())
    # ### end Alembic commands ###
