"""Add missing fields to users table

Revision ID: 1a1d5630f003
Revises: c063cff3718d
Create Date: 2025-10-24 15:40:59.530083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1d5630f003'
down_revision = 'c063cff3718d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('analytics_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('activity_log', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('device_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_info')
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'activity_log')
    op.drop_column('users', 'analytics_data')
    # ### end Alembic commands ###
