"""add_duration_fields_to_episodes_seasons_qualities

Revision ID: 227d71229ceb
Revises: e98c8e2f9736
Create Date: 2025-09-18 00:32:00.272778

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "227d71229ceb"
down_revision = "e98c8e2f9736"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "episode_qualities", sa.Column("duration_seconds", sa.Float(), nullable=True)
    )
    op.add_column(
        "seasons", sa.Column("total_duration_minutes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "seasons", sa.Column("average_episode_duration", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seasons", "average_episode_duration")
    op.drop_column("seasons", "total_duration_minutes")
    op.drop_column("episode_qualities", "duration_seconds")
    # ### end Alembic commands ###
