"""add_job_title_to_content_cast

Revision ID: 26a904270f97
Revises: dbd42bb8ab1c
Create Date: 2025-10-08 18:50:27.459482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a904270f97'
down_revision = 'dbd42bb8ab1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_cast', sa.Column('job_title', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_content_cast_job_title'), 'content_cast', ['job_title'], unique=False)
    op.alter_column('content_crew', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_content_crew_job_title'), 'content_crew', ['job_title'], unique=False)
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_content_crew_job_title'), table_name='content_crew')
    op.alter_column('content_crew', 'job_title',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_content_cast_job_title'), table_name='content_cast')
    op.drop_column('content_cast', 'job_title')
    # ### end Alembic commands ###
