"""Add user watch progress table for continue watching feature

Revision ID: 2dc0e43555de
Revises: 10fe6a765dc9
Create Date: 2025-10-19 23:30:46.643024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc0e43555de'
down_revision = '10fe6a765dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: faqs table already exists from previous migration, skipping creation
    op.create_table('user_watch_progress',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('current_position_seconds', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('watch_percentage', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_watch_progress_content_id', 'user_watch_progress', ['content_id'], unique=False)
    op.create_index('idx_user_watch_progress_last_watched', 'user_watch_progress', ['last_watched_at'], unique=False)
    op.create_index('idx_user_watch_progress_user_content', 'user_watch_progress', ['user_id', 'content_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_episode', 'user_watch_progress', ['user_id', 'episode_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_id', 'user_watch_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_watch_progress_is_deleted'), 'user_watch_progress', ['is_deleted'], unique=False)
    # Note: ad_campaigns columns and streaming_channels category already exist from previous migrations, skipping
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: ad_campaigns columns and streaming_channels category should not be dropped as they were created in previous migrations
    op.drop_index(op.f('ix_user_watch_progress_is_deleted'), table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_id', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_episode', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_content', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_last_watched', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_content_id', table_name='user_watch_progress')
    op.drop_table('user_watch_progress')
    # Note: faqs table should not be dropped as it was created in previous migration
    # ### end Alembic commands ###
