"""Add user watch progress table for continue watching feature

Revision ID: 2dc0e43555de
Revises: 10fe6a765dc9
Create Date: 2025-10-19 23:30:46.643024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc0e43555de'
down_revision = '10fe6a765dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_is_deleted'), 'faqs', ['is_deleted'], unique=False)
    op.create_table('user_watch_progress',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('current_position_seconds', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('watch_percentage', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_watch_progress_content_id', 'user_watch_progress', ['content_id'], unique=False)
    op.create_index('idx_user_watch_progress_last_watched', 'user_watch_progress', ['last_watched_at'], unique=False)
    op.create_index('idx_user_watch_progress_user_content', 'user_watch_progress', ['user_id', 'content_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_episode', 'user_watch_progress', ['user_id', 'episode_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_id', 'user_watch_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_watch_progress_is_deleted'), 'user_watch_progress', ['is_deleted'], unique=False)
    op.add_column('ad_campaigns', sa.Column('target_platform', sa.Enum('WEB', 'ANDROID', 'IOS', 'SMART_TV', 'OTHER', name='platformtype'), nullable=False))
    op.add_column('ad_campaigns', sa.Column('ad_type', sa.Enum('BANNER', 'VIDEO', 'NATIVE', 'INTERSTITIAL', 'OTHER', name='adtype'), nullable=False))
    op.add_column('ad_campaigns', sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'DRAFT', name='campaignstatus'), nullable=False))
    op.create_index(op.f('ix_ad_campaigns_ad_type'), 'ad_campaigns', ['ad_type'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_status'), 'ad_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_target_platform'), 'ad_campaigns', ['target_platform'], unique=False)
    op.add_column('streaming_channels', sa.Column('category', sa.Enum('NEWS', 'SPORTS', 'ENTERTAINMENT', 'RELIGIOUS', 'KIDS', 'DOCUMENTARY', 'MOVIES', 'MUSIC', 'EDUCATIONAL', 'LIFESTYLE', name='streamingchannelcategory'), nullable=True))
    op.create_index(op.f('ix_streaming_channels_category'), 'streaming_channels', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_channels_category'), table_name='streaming_channels')
    op.drop_column('streaming_channels', 'category')
    op.drop_index(op.f('ix_ad_campaigns_target_platform'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_status'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_ad_type'), table_name='ad_campaigns')
    op.drop_column('ad_campaigns', 'status')
    op.drop_column('ad_campaigns', 'ad_type')
    op.drop_column('ad_campaigns', 'target_platform')
    op.drop_index(op.f('ix_user_watch_progress_is_deleted'), table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_id', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_episode', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_content', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_last_watched', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_content_id', table_name='user_watch_progress')
    op.drop_table('user_watch_progress')
    op.drop_index(op.f('ix_faqs_is_deleted'), table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
