"""add food tables

Revision ID: 404e71a4e9f1
Revises: 4523fd1381f5
Create Date: 2025-11-18 12:58:43.369595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404e71a4e9f1'
down_revision: Union[str, Sequence[str], None] = '4523fd1381f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuisines_is_deleted'), 'cuisines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_cuisines_name'), 'cuisines', ['name'], unique=True)
    op.create_table('moods',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moods_is_deleted'), 'moods', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_moods_name'), 'moods', ['name'], unique=True)
    op.create_table('restaurants',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    op.create_index(op.f('ix_restaurants_is_deleted'), 'restaurants', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_restaurants_latitude'), 'restaurants', ['latitude'], unique=False)
    op.create_index(op.f('ix_restaurants_longitude'), 'restaurants', ['longitude'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_rating'), 'restaurants', ['rating'], unique=False)
    op.create_table('dishes',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('cuisine_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('featured_week', sa.Date(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('preparation_time_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_cuisine_id'), 'dishes', ['cuisine_id'], unique=False)
    op.create_index(op.f('ix_dishes_featured_week'), 'dishes', ['featured_week'], unique=False)
    op.create_index(op.f('ix_dishes_is_deleted'), 'dishes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dishes_is_featured'), 'dishes', ['is_featured'], unique=False)
    op.create_index(op.f('ix_dishes_name'), 'dishes', ['name'], unique=False)
    op.create_index(op.f('ix_dishes_rating'), 'dishes', ['rating'], unique=False)
    op.create_index(op.f('ix_dishes_restaurant_id'), 'dishes', ['restaurant_id'], unique=False)
    op.create_table('reservations',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('reservation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'reservation_time', 'customer_email', name='uq_reservation_unique_slot')
    )
    op.create_index(op.f('ix_reservations_customer_email'), 'reservations', ['customer_email'], unique=False)
    op.create_index(op.f('ix_reservations_is_deleted'), 'reservations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reservations_restaurant_id'), 'reservations', ['restaurant_id'], unique=False)
    op.create_table('dish_moods',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('mood_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'mood_id'),
    sa.UniqueConstraint('dish_id', 'mood_id', name='uq_dish_mood')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish_moods')
    op.drop_index(op.f('ix_reservations_restaurant_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_is_deleted'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_customer_email'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_dishes_restaurant_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_rating'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_name'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_is_featured'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_is_deleted'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_featured_week'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_cuisine_id'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_restaurants_rating'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_longitude'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_latitude'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_is_deleted'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_moods_name'), table_name='moods')
    op.drop_index(op.f('ix_moods_is_deleted'), table_name='moods')
    op.drop_table('moods')
    op.drop_index(op.f('ix_cuisines_name'), table_name='cuisines')
    op.drop_index(op.f('ix_cuisines_is_deleted'), table_name='cuisines')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
