"""add_profile_id_to_user_content_interactions

Revision ID: 4d79bac7d1bc
Revises: e101b8cce52d
Create Date: 2025-10-24 18:17:00.326712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d79bac7d1bc'
down_revision = 'e101b8cce52d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content_interactions', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_content_interactions_profile_id'), 'user_content_interactions', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'user_content_interactions', 'user_profiles', ['profile_id'], ['id'])
    op.add_column('user_watch_history', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_watch_history_profile_id'), 'user_watch_history', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'user_watch_history', 'user_profiles', ['profile_id'], ['id'])
    op.add_column('user_watch_progress', sa.Column('profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user_watch_progress', 'user_profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_watch_progress', type_='foreignkey')
    op.drop_column('user_watch_progress', 'profile_id')
    op.drop_constraint(None, 'user_watch_history', type_='foreignkey')
    op.drop_index(op.f('ix_user_watch_history_profile_id'), table_name='user_watch_history')
    op.drop_column('user_watch_history', 'profile_id')
    op.drop_constraint(None, 'user_content_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_user_content_interactions_profile_id'), table_name='user_content_interactions')
    op.drop_column('user_content_interactions', 'profile_id')
    # ### end Alembic commands ###
