"""add_profile_id_to_user_content_interactions

Revision ID: 4d79bac7d1bc
Revises: e101b8cce52d
Create Date: 2025-10-24 18:17:00.326712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d79bac7d1bc'
down_revision = 'e101b8cce52d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, create the user_profiles table if it doesn't exist
    op.create_table(
        'user_profiles',
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('profile_type', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('is_kids_profile', sa.Boolean(), nullable=False),
        sa.Column('age_rating_limit', sa.Integer(), nullable=False),
        sa.Column('language_preference', sa.String(length=10), nullable=False),
        sa.Column('subtitle_preference', sa.String(length=10), nullable=False),
        sa.Column('parental_controls_enabled', sa.Boolean(), nullable=False),
        sa.Column('content_restrictions', sa.Text(), nullable=True),
        sa.Column('viewing_time_limit', sa.Integer(), nullable=True),
        sa.Column('bedtime_start', sa.String(length=5), nullable=True),
        sa.Column('bedtime_end', sa.String(length=5), nullable=True),
        sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    
    # Now add the profile_id columns and foreign keys
    op.add_column('user_content_interactions', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_content_interactions_profile_id'), 'user_content_interactions', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'user_content_interactions', 'user_profiles', ['profile_id'], ['id'])
    op.add_column('user_watch_history', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_watch_history_profile_id'), 'user_watch_history', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'user_watch_history', 'user_profiles', ['profile_id'], ['id'])
    op.add_column('user_watch_progress', sa.Column('profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user_watch_progress', 'user_profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_watch_progress', type_='foreignkey')
    op.drop_column('user_watch_progress', 'profile_id')
    op.drop_constraint(None, 'user_watch_history', type_='foreignkey')
    op.drop_index(op.f('ix_user_watch_history_profile_id'), table_name='user_watch_history')
    op.drop_column('user_watch_history', 'profile_id')
    op.drop_constraint(None, 'user_content_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_user_content_interactions_profile_id'), table_name='user_content_interactions')
    op.drop_column('user_content_interactions', 'profile_id')
    
    # Drop the user_profiles table
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
