"""Add streaming channels table

Revision ID: 5089981dcce0
Revises: cce001799cb4
Create Date: 2025-09-24 01:32:28.081351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5089981dcce0'
down_revision = 'cce001799cb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_channels',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_hd', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_channels_category'), 'streaming_channels', ['category'], unique=False)
    op.create_index(op.f('ix_streaming_channels_country'), 'streaming_channels', ['country'], unique=False)
    op.create_index(op.f('ix_streaming_channels_is_active'), 'streaming_channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_streaming_channels_is_deleted'), 'streaming_channels', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_streaming_channels_is_featured'), 'streaming_channels', ['is_featured'], unique=False)
    op.create_index(op.f('ix_streaming_channels_language'), 'streaming_channels', ['language'], unique=False)
    op.create_index(op.f('ix_streaming_channels_name'), 'streaming_channels', ['name'], unique=False)
    op.create_index(op.f('ix_streaming_channels_sort_order'), 'streaming_channels', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_channels_sort_order'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_name'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_language'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_is_featured'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_is_deleted'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_is_active'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_country'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_category'), table_name='streaming_channels')
    op.drop_table('streaming_channels')
    # ### end Alembic commands ###
