"""add_password_reset_otp_table

Revision ID: 6497e1a2b872
Revises: 227d71229ceb
Create Date: 2025-09-18 23:31:40.109821

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6497e1a2b872"
down_revision = "227d71229ceb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_otps",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("otp_code", sa.String(length=6), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_otps_email"),
        "password_reset_otps",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_otps_is_deleted"),
        "password_reset_otps",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_otps_is_used"),
        "password_reset_otps",
        ["is_used"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_otps_otp_code"),
        "password_reset_otps",
        ["otp_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_otps_user_id"),
        "password_reset_otps",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_password_reset_otps_user_id"), table_name="password_reset_otps"
    )
    op.drop_index(
        op.f("ix_password_reset_otps_otp_code"), table_name="password_reset_otps"
    )
    op.drop_index(
        op.f("ix_password_reset_otps_is_used"), table_name="password_reset_otps"
    )
    op.drop_index(
        op.f("ix_password_reset_otps_is_deleted"), table_name="password_reset_otps"
    )
    op.drop_index(
        op.f("ix_password_reset_otps_email"), table_name="password_reset_otps"
    )
    op.drop_table("password_reset_otps")
    # ### end Alembic commands ###
