"""Remove unused fields from streaming channels

Revision ID: 713b4303f20e
Revises: 0cbc8661522b
Create Date: 2025-09-24 02:07:52.608928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713b4303f20e'
down_revision = '0cbc8661522b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_channels_is_active'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_is_featured'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_sort_order'), table_name='streaming_channels')
    op.drop_column('streaming_channels', 'is_hd')
    op.drop_column('streaming_channels', 'is_active')
    op.drop_column('streaming_channels', 'is_featured')
    op.drop_column('streaming_channels', 'sort_order')
    op.drop_column('streaming_channels', 'view_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaming_channels', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('streaming_channels', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('streaming_channels', sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('streaming_channels', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('streaming_channels', sa.Column('is_hd', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_streaming_channels_sort_order'), 'streaming_channels', ['sort_order'], unique=False)
    op.create_index(op.f('ix_streaming_channels_is_featured'), 'streaming_channels', ['is_featured'], unique=False)
    op.create_index(op.f('ix_streaming_channels_is_active'), 'streaming_channels', ['is_active'], unique=False)
    # ### end Alembic commands ###
