"""Initial migration - create all tables

Revision ID: 77afbce47b46
Revises:
Create Date: 2025-09-15 23:40:55.038736

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "77afbce47b46"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contents",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tagline", sa.String(length=500), nullable=True),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_rating", sa.String(length=10), nullable=True),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.Column("backdrop_url", sa.String(length=500), nullable=True),
        sa.Column("trailer_url", sa.String(length=500), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("thumbnail_grid", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("premiere_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("imdb_rating", sa.Float(), nullable=True),
        sa.Column("imdb_votes", sa.Integer(), nullable=True),
        sa.Column("stream_vibe", sa.Float(), nullable=True),
        sa.Column("stream_vibe_votes", sa.Integer(), nullable=True),
        sa.Column("platform_rating", sa.Float(), nullable=True),
        sa.Column("platform_votes", sa.Integer(), nullable=False),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("original_language", sa.String(length=10), nullable=True),
        sa.Column("spoken_languages", sa.Text(), nullable=True),
        sa.Column("total_seasons", sa.Integer(), nullable=False),
        sa.Column("total_episodes", sa.Integer(), nullable=False),
        sa.Column("is_ongoing", sa.Boolean(), nullable=False),
        sa.Column("next_episode_date", sa.Date(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_trending", sa.Boolean(), nullable=False),
        sa.Column("is_new_release", sa.Boolean(), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("geographic_restrictions", sa.Text(), nullable=True),
        sa.Column("total_views", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("reviews_count", sa.Integer(), nullable=False),
        sa.Column("average_completion_rate", sa.Float(), nullable=True),
        sa.Column("average_rating", sa.Float(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("search_keywords", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contents_content_type"), "contents", ["content_type"], unique=False
    )
    op.create_index(
        op.f("ix_contents_is_deleted"), "contents", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_contents_is_featured"), "contents", ["is_featured"], unique=False
    )
    op.create_index(
        op.f("ix_contents_is_new_release"), "contents", ["is_new_release"], unique=False
    )
    op.create_index(
        op.f("ix_contents_is_premium"), "contents", ["is_premium"], unique=False
    )
    op.create_index(
        op.f("ix_contents_is_trending"), "contents", ["is_trending"], unique=False
    )
    op.create_index(
        op.f("ix_contents_language"), "contents", ["language"], unique=False
    )
    op.create_index(
        op.f("ix_contents_likes_count"), "contents", ["likes_count"], unique=False
    )
    op.create_index(
        op.f("ix_contents_platform_rating"),
        "contents",
        ["platform_rating"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contents_release_date"), "contents", ["release_date"], unique=False
    )
    op.create_index(
        op.f("ix_contents_reviews_count"), "contents", ["reviews_count"], unique=False
    )
    op.create_index(op.f("ix_contents_slug"), "contents", ["slug"], unique=True)
    op.create_index(op.f("ix_contents_status"), "contents", ["status"], unique=False)
    op.create_index(op.f("ix_contents_title"), "contents", ["title"], unique=False)
    op.create_index(
        op.f("ix_contents_total_views"), "contents", ["total_views"], unique=False
    )
    op.create_table(
        "genres",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_name", sa.String(length=100), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("parent_genre_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("content_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_genre_id"],
            ["genres.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genres_is_active"), "genres", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_genres_is_deleted"), "genres", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_genres_name"), "genres", ["name"], unique=True)
    op.create_index(op.f("ix_genres_slug"), "genres", ["slug"], unique=True)
    op.create_table(
        "people",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=300), nullable=False),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("death_date", sa.Date(), nullable=True),
        sa.Column("birth_place", sa.String(length=255), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("known_for_department", sa.String(length=100), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_people_is_deleted"), "people", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_people_name"), "people", ["name"], unique=False)
    op.create_index(op.f("ix_people_slug"), "people", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False
        ),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True
        ),
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("profile_status", sa.String(length=30), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "avatar_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_users_profile_status"), "users", ["profile_status"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "content_cast",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("character_name", sa.String(length=255), nullable=True),
        sa.Column("cast_order", sa.Integer(), nullable=False),
        sa.Column("is_main_cast", sa.Boolean(), nullable=False),
        sa.Column("character_image_url", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
        ),
        sa.PrimaryKeyConstraint("id", "content_id", "person_id"),
    )
    op.create_table(
        "content_crew",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("job_title", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("credit_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
        ),
        sa.PrimaryKeyConstraint("id", "content_id", "person_id"),
    )
    op.create_table(
        "content_genres",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("genre_id", sa.UUID(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.PrimaryKeyConstraint("id", "content_id", "genre_id"),
    )
    op.create_table(
        "content_reviews",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("helpful_votes", sa.Integer(), nullable=False),
        sa.Column("total_votes", sa.Integer(), nullable=False),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id", "user_id", name="unique_user_content_review"),
    )
    op.create_index(
        op.f("ix_content_reviews_content_id"),
        "content_reviews",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_reviews_is_deleted"),
        "content_reviews",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_reviews_status"), "content_reviews", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_content_reviews_user_id"), "content_reviews", ["user_id"], unique=False
    )
    op.create_table(
        "content_views",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("viewer_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["viewer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_views_content_id"),
        "content_views",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_views_is_deleted"),
        "content_views",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_views_viewer_id"), "content_views", ["viewer_id"], unique=False
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_verification_tokens_email"),
        "email_verification_tokens",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_is_deleted"),
        "email_verification_tokens",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_is_used"),
        "email_verification_tokens",
        ["is_used"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_token"),
        "email_verification_tokens",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_user_id"),
        "email_verification_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "movie_files",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("quality_level", sa.String(length=10), nullable=False),
        sa.Column("resolution_width", sa.Integer(), nullable=False),
        sa.Column("resolution_height", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("bitrate_kbps", sa.Integer(), nullable=True),
        sa.Column("video_codec", sa.String(length=50), nullable=True),
        sa.Column("audio_codec", sa.String(length=50), nullable=True),
        sa.Column("container_format", sa.String(length=20), nullable=True),
        sa.Column("storage_bucket", sa.String(length=255), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("storage_region", sa.String(length=50), nullable=True),
        sa.Column("cdn_url", sa.String(length=500), nullable=True),
        sa.Column("is_ready", sa.Boolean(), nullable=False),
        sa.Column("subtitle_tracks", sa.Text(), nullable=True),
        sa.Column("audio_tracks", sa.Text(), nullable=True),
        sa.Column("available_languages", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id", "quality_level", name="unique_movie_quality"),
    )
    op.create_index(
        op.f("ix_movie_files_content_id"), "movie_files", ["content_id"], unique=False
    )
    op.create_index(
        op.f("ix_movie_files_is_deleted"), "movie_files", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_movie_files_is_ready"), "movie_files", ["is_ready"], unique=False
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_is_deleted"),
        "password_reset_tokens",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_is_used"),
        "password_reset_tokens",
        ["is_used"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token"),
        "password_reset_tokens",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_family", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.String(length=255), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("parent_token_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_is_deleted"),
        "refresh_tokens",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_family"),
        "refresh_tokens",
        ["token_family"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "seasons",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.Column("backdrop_url", sa.String(length=500), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_id", "season_number", name="unique_content_season"
        ),
    )
    op.create_index(op.f("ix_seasons_air_date"), "seasons", ["air_date"], unique=False)
    op.create_index(
        op.f("ix_seasons_content_id"), "seasons", ["content_id"], unique=False
    )
    op.create_index(
        op.f("ix_seasons_is_deleted"), "seasons", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_seasons_season_number"), "seasons", ["season_number"], unique=False
    )
    op.create_table(
        "token_blacklist",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("revoked_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_blacklist_is_deleted"),
        "token_blacklist",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_blacklist_token"), "token_blacklist", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_token_blacklist_user_id"), "token_blacklist", ["user_id"], unique=False
    )
    op.create_table(
        "tokens",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_family", sa.UUID(), nullable=True),
        sa.Column("device_id", sa.String(length=255), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("scope", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokens_is_deleted"), "tokens", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_tokens_token"), "tokens", ["token"], unique=False)
    op.create_index(
        op.f("ix_tokens_token_family"), "tokens", ["token_family"], unique=False
    )
    op.create_index(op.f("ix_tokens_user_id"), "tokens", ["user_id"], unique=False)
    op.create_table(
        "user_content_interactions",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("interaction_type", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "content_id",
            "interaction_type",
            name="unique_user_content_interaction",
        ),
    )
    op.create_index(
        op.f("ix_user_content_interactions_content_id"),
        "user_content_interactions",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_content_interactions_interaction_type"),
        "user_content_interactions",
        ["interaction_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_content_interactions_is_deleted"),
        "user_content_interactions",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_content_interactions_user_id"),
        "user_content_interactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "episodes",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tag_line", sa.Text(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("video_file_url", sa.String(length=500), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=True),
        sa.Column("preview_url", sa.String(length=500), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("video_codec", sa.String(length=50), nullable=True),
        sa.Column("audio_codec", sa.String(length=50), nullable=True),
        sa.Column("container_format", sa.String(length=20), nullable=True),
        sa.Column("bitrate_kbps", sa.Integer(), nullable=True),
        sa.Column("frame_rate", sa.Float(), nullable=True),
        sa.Column("storage_bucket", sa.String(length=255), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("storage_region", sa.String(length=50), nullable=True),
        sa.Column("cdn_url", sa.String(length=500), nullable=True),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("subtitle_tracks", sa.Text(), nullable=True),
        sa.Column("audio_tracks", sa.Text(), nullable=True),
        sa.Column("available_languages", sa.Text(), nullable=True),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("average_completion_rate", sa.Float(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_id", "season_id", "episode_number", name="unique_season_episode"
        ),
        sa.UniqueConstraint("content_id", "slug", name="unique_content_episode_slug"),
    )
    op.create_index(
        op.f("ix_episodes_air_date"), "episodes", ["air_date"], unique=False
    )
    op.create_index(
        op.f("ix_episodes_content_id"), "episodes", ["content_id"], unique=False
    )
    op.create_index(
        op.f("ix_episodes_episode_number"), "episodes", ["episode_number"], unique=False
    )
    op.create_index(
        op.f("ix_episodes_is_available"), "episodes", ["is_available"], unique=False
    )
    op.create_index(
        op.f("ix_episodes_is_deleted"), "episodes", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_episodes_processing_status"),
        "episodes",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episodes_season_id"), "episodes", ["season_id"], unique=False
    )
    op.create_index(op.f("ix_episodes_slug"), "episodes", ["slug"], unique=False)
    op.create_index(
        op.f("ix_episodes_views_count"), "episodes", ["views_count"], unique=False
    )
    op.create_table(
        "episode_qualities",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("episode_id", sa.UUID(), nullable=False),
        sa.Column("quality_level", sa.String(length=10), nullable=False),
        sa.Column("resolution_width", sa.Integer(), nullable=False),
        sa.Column("resolution_height", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("bitrate_kbps", sa.Integer(), nullable=True),
        sa.Column("video_codec", sa.String(length=50), nullable=True),
        sa.Column("storage_bucket", sa.String(length=255), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("cdn_url", sa.String(length=500), nullable=True),
        sa.Column("is_ready", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "episode_id", "quality_level", name="unique_episode_quality"
        ),
    )
    op.create_index(
        op.f("ix_episode_qualities_episode_id"),
        "episode_qualities",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_qualities_is_deleted"),
        "episode_qualities",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_qualities_is_ready"),
        "episode_qualities",
        ["is_ready"],
        unique=False,
    )
    op.create_table(
        "episode_views",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("episode_id", sa.UUID(), nullable=False),
        sa.Column("viewer_id", sa.UUID(), nullable=True),
        sa.Column("quality_watched", sa.String(length=10), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("is_binge_watch", sa.Boolean(), nullable=False),
        sa.Column("came_from_episode_id", sa.UUID(), nullable=True),
        sa.Column("subtitle_language", sa.String(length=10), nullable=True),
        sa.Column("audio_language", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["came_from_episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["viewer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_episode_views_episode_id"),
        "episode_views",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_views_is_deleted"),
        "episode_views",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_views_session_id"),
        "episode_views",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_views_viewer_id"), "episode_views", ["viewer_id"], unique=False
    )
    op.create_table(
        "user_watch_history",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("current_episode_id", sa.UUID(), nullable=True),
        sa.Column("current_position_seconds", sa.Integer(), nullable=False),
        sa.Column("total_episodes_watched", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("is_currently_watching", sa.Boolean(), nullable=False),
        sa.Column("first_watched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_watched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preferred_quality", sa.String(length=10), nullable=True),
        sa.Column("preferred_subtitle_language", sa.String(length=10), nullable=True),
        sa.Column("preferred_audio_language", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "content_id", name="unique_user_content_history"
        ),
    )
    op.create_index(
        op.f("ix_user_watch_history_content_id"),
        "user_watch_history",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_watch_history_is_deleted"),
        "user_watch_history",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_watch_history_last_watched_at"),
        "user_watch_history",
        ["last_watched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_watch_history_user_id"),
        "user_watch_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "watch_sessions",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("quality_setting", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_watch_sessions_content_id"),
        "watch_sessions",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_sessions_episode_id"),
        "watch_sessions",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_sessions_is_deleted"),
        "watch_sessions",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_sessions_session_id"),
        "watch_sessions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_sessions_user_id"), "watch_sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watch_sessions_user_id"), table_name="watch_sessions")
    op.drop_index(op.f("ix_watch_sessions_session_id"), table_name="watch_sessions")
    op.drop_index(op.f("ix_watch_sessions_is_deleted"), table_name="watch_sessions")
    op.drop_index(op.f("ix_watch_sessions_episode_id"), table_name="watch_sessions")
    op.drop_index(op.f("ix_watch_sessions_content_id"), table_name="watch_sessions")
    op.drop_table("watch_sessions")
    op.drop_index(
        op.f("ix_user_watch_history_user_id"), table_name="user_watch_history"
    )
    op.drop_index(
        op.f("ix_user_watch_history_last_watched_at"), table_name="user_watch_history"
    )
    op.drop_index(
        op.f("ix_user_watch_history_is_deleted"), table_name="user_watch_history"
    )
    op.drop_index(
        op.f("ix_user_watch_history_content_id"), table_name="user_watch_history"
    )
    op.drop_table("user_watch_history")
    op.drop_index(op.f("ix_episode_views_viewer_id"), table_name="episode_views")
    op.drop_index(op.f("ix_episode_views_session_id"), table_name="episode_views")
    op.drop_index(op.f("ix_episode_views_is_deleted"), table_name="episode_views")
    op.drop_index(op.f("ix_episode_views_episode_id"), table_name="episode_views")
    op.drop_table("episode_views")
    op.drop_index(op.f("ix_episode_qualities_is_ready"), table_name="episode_qualities")
    op.drop_index(
        op.f("ix_episode_qualities_is_deleted"), table_name="episode_qualities"
    )
    op.drop_index(
        op.f("ix_episode_qualities_episode_id"), table_name="episode_qualities"
    )
    op.drop_table("episode_qualities")
    op.drop_index(op.f("ix_episodes_views_count"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_slug"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_season_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_processing_status"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_is_deleted"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_is_available"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_episode_number"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_content_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_air_date"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_index(
        op.f("ix_user_content_interactions_user_id"),
        table_name="user_content_interactions",
    )
    op.drop_index(
        op.f("ix_user_content_interactions_is_deleted"),
        table_name="user_content_interactions",
    )
    op.drop_index(
        op.f("ix_user_content_interactions_interaction_type"),
        table_name="user_content_interactions",
    )
    op.drop_index(
        op.f("ix_user_content_interactions_content_id"),
        table_name="user_content_interactions",
    )
    op.drop_table("user_content_interactions")
    op.drop_index(op.f("ix_tokens_user_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_token_family"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_token"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_is_deleted"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_token_blacklist_user_id"), table_name="token_blacklist")
    op.drop_index(op.f("ix_token_blacklist_token"), table_name="token_blacklist")
    op.drop_index(op.f("ix_token_blacklist_is_deleted"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    op.drop_index(op.f("ix_seasons_season_number"), table_name="seasons")
    op.drop_index(op.f("ix_seasons_is_deleted"), table_name="seasons")
    op.drop_index(op.f("ix_seasons_content_id"), table_name="seasons")
    op.drop_index(op.f("ix_seasons_air_date"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_family"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_is_deleted"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_is_used"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_is_deleted"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_movie_files_is_ready"), table_name="movie_files")
    op.drop_index(op.f("ix_movie_files_is_deleted"), table_name="movie_files")
    op.drop_index(op.f("ix_movie_files_content_id"), table_name="movie_files")
    op.drop_table("movie_files")
    op.drop_index(
        op.f("ix_email_verification_tokens_user_id"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_token"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_is_used"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_is_deleted"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_email"),
        table_name="email_verification_tokens",
    )
    op.drop_table("email_verification_tokens")
    op.drop_index(op.f("ix_content_views_viewer_id"), table_name="content_views")
    op.drop_index(op.f("ix_content_views_is_deleted"), table_name="content_views")
    op.drop_index(op.f("ix_content_views_content_id"), table_name="content_views")
    op.drop_table("content_views")
    op.drop_index(op.f("ix_content_reviews_user_id"), table_name="content_reviews")
    op.drop_index(op.f("ix_content_reviews_status"), table_name="content_reviews")
    op.drop_index(op.f("ix_content_reviews_is_deleted"), table_name="content_reviews")
    op.drop_index(op.f("ix_content_reviews_content_id"), table_name="content_reviews")
    op.drop_table("content_reviews")
    op.drop_table("content_genres")
    op.drop_table("content_crew")
    op.drop_table("content_cast")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_profile_status"), table_name="users")
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_people_slug"), table_name="people")
    op.drop_index(op.f("ix_people_name"), table_name="people")
    op.drop_index(op.f("ix_people_is_deleted"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_genres_slug"), table_name="genres")
    op.drop_index(op.f("ix_genres_name"), table_name="genres")
    op.drop_index(op.f("ix_genres_is_deleted"), table_name="genres")
    op.drop_index(op.f("ix_genres_is_active"), table_name="genres")
    op.drop_table("genres")
    op.drop_index(op.f("ix_contents_total_views"), table_name="contents")
    op.drop_index(op.f("ix_contents_title"), table_name="contents")
    op.drop_index(op.f("ix_contents_status"), table_name="contents")
    op.drop_index(op.f("ix_contents_slug"), table_name="contents")
    op.drop_index(op.f("ix_contents_reviews_count"), table_name="contents")
    op.drop_index(op.f("ix_contents_release_date"), table_name="contents")
    op.drop_index(op.f("ix_contents_platform_rating"), table_name="contents")
    op.drop_index(op.f("ix_contents_likes_count"), table_name="contents")
    op.drop_index(op.f("ix_contents_language"), table_name="contents")
    op.drop_index(op.f("ix_contents_is_trending"), table_name="contents")
    op.drop_index(op.f("ix_contents_is_premium"), table_name="contents")
    op.drop_index(op.f("ix_contents_is_new_release"), table_name="contents")
    op.drop_index(op.f("ix_contents_is_featured"), table_name="contents")
    op.drop_index(op.f("ix_contents_is_deleted"), table_name="contents")
    op.drop_index(op.f("ix_contents_content_type"), table_name="contents")
    op.drop_table("contents")
    # ### end Alembic commands ###
