"""add_user_favorites_table

Revision ID: 80ed555ac3f1
Revises: 6f096afd1a59
Create Date: 2025-11-19 13:06:18.498126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ed555ac3f1'
down_revision: Union[str, Sequence[str], None] = '6f096afd1a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dish_id', name='uq_user_dish_favorite')
    )
    op.create_index(op.f('ix_user_favorites_dish_id'), 'user_favorites', ['dish_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_is_deleted'), 'user_favorites', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_is_deleted'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_dish_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    # ### end Alembic commands ###
