"""add_faqs_table

Revision ID: 89be161b4482
Revises: de5d1ac06c9d
Create Date: 2025-11-13 16:02:30.379678

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '89be161b4482'
down_revision = 'de5d1ac06c9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.create_index(op.f('ix_faqs_is_deleted'), 'faqs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_faqs_is_published'), 'faqs', ['is_published'], unique=False)
    op.create_index(op.f('ix_faqs_order'), 'faqs', ['order'], unique=False)
    op.create_index(op.f('ix_faqs_question'), 'faqs', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faqs_question'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_order'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_is_published'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_is_deleted'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
