"""sync current schema

Revision ID: 9037d106b503
Revises: c059e264fcf2
Create Date: 2025-10-29 12:53:47.168132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9037d106b503'
down_revision = 'c059e264fcf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
