"""add_description_field_to_policies

Revision ID: b4970b5c526b
Revises: ac80946784d7
Create Date: 2025-10-13 13:09:03.085415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4970b5c526b'
down_revision = 'ac80946784d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('description', sa.String(length=4000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'description')
    # ### end Alembic commands ###
