"""add moviesources table

Revision ID: b96deb24fddd
Revises: 61937bab565e
Create Date: 2025-11-05 15:39:50.943223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96deb24fddd'
down_revision = '61937bab565e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moviesources',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moviesources_active', 'moviesources', ['active'], unique=False)
    op.create_index(op.f('ix_moviesources_is_deleted'), 'moviesources', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moviesources_is_deleted'), table_name='moviesources')
    op.drop_index('ix_moviesources_active', table_name='moviesources')
    op.drop_table('moviesources')
    # ### end Alembic commands ###
