"""Initial migration

Revision ID: b9a12917d7b6
Revises: 
Create Date: 2025-10-29 17:22:45.728471

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b9a12917d7b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_campaigns',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_platform', sa.Enum('WEB', 'ANDROID', 'IOS', 'SMART_TV', 'OTHER', name='platformtype'), nullable=False),
    sa.Column('ad_type', sa.Enum('BANNER', 'VIDEO', 'NATIVE', 'INTERSTITIAL', 'OTHER', name='adtype'), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'DRAFT', name='campaignstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_ad_type'), 'ad_campaigns', ['ad_type'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_is_deleted'), 'ad_campaigns', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_status'), 'ad_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_target_platform'), 'ad_campaigns', ['target_platform'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_title'), 'ad_campaigns', ['title'], unique=False)
    op.create_table('contents',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_rating', sa.String(length=10), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('trailer_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_grid', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('premiere_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('imdb_votes', sa.Integer(), nullable=True),
    sa.Column('stream_vibe', sa.Float(), nullable=True),
    sa.Column('stream_vibe_votes', sa.Integer(), nullable=True),
    sa.Column('platform_rating', sa.Float(), nullable=True),
    sa.Column('platform_votes', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('spoken_languages', sa.Text(), nullable=True),
    sa.Column('total_seasons', sa.Integer(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=False),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.Column('next_episode_date', sa.Date(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('is_new_release', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geographic_restrictions', sa.Text(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('average_completion_rate', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('search_keywords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_content_type'), 'contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_contents_is_deleted'), 'contents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_contents_is_featured'), 'contents', ['is_featured'], unique=False)
    op.create_index(op.f('ix_contents_is_new_release'), 'contents', ['is_new_release'], unique=False)
    op.create_index(op.f('ix_contents_is_premium'), 'contents', ['is_premium'], unique=False)
    op.create_index(op.f('ix_contents_is_trending'), 'contents', ['is_trending'], unique=False)
    op.create_index(op.f('ix_contents_language'), 'contents', ['language'], unique=False)
    op.create_index(op.f('ix_contents_likes_count'), 'contents', ['likes_count'], unique=False)
    op.create_index(op.f('ix_contents_platform_rating'), 'contents', ['platform_rating'], unique=False)
    op.create_index(op.f('ix_contents_release_date'), 'contents', ['release_date'], unique=False)
    op.create_index(op.f('ix_contents_reviews_count'), 'contents', ['reviews_count'], unique=False)
    op.create_index(op.f('ix_contents_slug'), 'contents', ['slug'], unique=True)
    op.create_index(op.f('ix_contents_status'), 'contents', ['status'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_total_views'), 'contents', ['total_views'], unique=False)
    op.create_table('faqs',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_is_deleted'), 'faqs', ['is_deleted'], unique=False)
    op.create_table('genres',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('parent_genre_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_is_active'), 'genres', ['is_active'], unique=False)
    op.create_index(op.f('ix_genres_is_deleted'), 'genres', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_table('people',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('known_for_department', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_is_deleted'), 'people', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_index(op.f('ix_people_slug'), 'people', ['slug'], unique=True)
    op.create_table('policies',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_author_id'), 'policies', ['author_id'], unique=False)
    op.create_index(op.f('ix_policies_is_active'), 'policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_policies_is_deleted'), 'policies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_policies_policy_type'), 'policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_policies_reviewer_id'), 'policies', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_policies_slug'), 'policies', ['slug'], unique=True)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_policies_title'), 'policies', ['title'], unique=False)
    op.create_table('streaming_channels',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('NEWS', 'SPORTS', 'ENTERTAINMENT', 'RELIGIOUS', 'KIDS', 'DOCUMENTARY', 'MOVIES', 'MUSIC', 'EDUCATIONAL', 'LIFESTYLE', name='streamingchannelcategory'), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_channels_category'), 'streaming_channels', ['category'], unique=False)
    op.create_index(op.f('ix_streaming_channels_country'), 'streaming_channels', ['country'], unique=False)
    op.create_index(op.f('ix_streaming_channels_is_deleted'), 'streaming_channels', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_streaming_channels_language'), 'streaming_channels', ['language'], unique=False)
    op.create_index(op.f('ix_streaming_channels_name'), 'streaming_channels', ['name'], unique=False)
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_event_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_webhook_events_event_type'), 'stripe_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_processed'), 'stripe_webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_stripe_event_id'), 'stripe_webhook_events', ['stripe_event_id'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analytics_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('profile_status', sa.String(length=30), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('signup_type', sa.String(length=20), nullable=False),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('apple_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_profile_status'), 'users', ['profile_status'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_signup_type'), 'users', ['signup_type'], unique=False)
    op.create_table('watch_history',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_history_content_id'), 'watch_history', ['content_id'], unique=False)
    op.create_index(op.f('ix_watch_history_episode_id'), 'watch_history', ['episode_id'], unique=False)
    op.create_index(op.f('ix_watch_history_is_deleted'), 'watch_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_watch_history_last_watched_at'), 'watch_history', ['last_watched_at'], unique=False)
    op.create_index(op.f('ix_watch_history_user_id'), 'watch_history', ['user_id'], unique=False)
    op.create_table('ad_campaign_stats',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaign_stats_campaign_id'), 'ad_campaign_stats', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_campaign_stats_is_deleted'), 'ad_campaign_stats', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ad_campaign_stats_stat_date'), 'ad_campaign_stats', ['stat_date'], unique=False)
    op.create_table('content_cast',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('cast_order', sa.Integer(), nullable=False),
    sa.Column('is_main_cast', sa.Boolean(), nullable=False),
    sa.Column('character_image_url', sa.String(length=500), nullable=True),
    sa.Column('job_title', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id', 'content_id', 'person_id')
    )
    op.create_index(op.f('ix_content_cast_job_title'), 'content_cast', ['job_title'], unique=False)
    op.create_table('content_crew',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('credit_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id', 'content_id', 'person_id')
    )
    op.create_index(op.f('ix_content_crew_job_title'), 'content_crew', ['job_title'], unique=False)
    op.create_table('content_genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id', 'content_id', 'genre_id')
    )
    op.create_table('content_reviews',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('helpful_votes', sa.Integer(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'user_id', name='unique_user_content_review')
    )
    op.create_index(op.f('ix_content_reviews_content_id'), 'content_reviews', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_reviews_is_deleted'), 'content_reviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_content_reviews_status'), 'content_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_content_reviews_user_id'), 'content_reviews', ['user_id'], unique=False)
    op.create_table('content_views',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_views_content_id'), 'content_views', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_views_is_deleted'), 'content_views', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_content_views_viewer_id'), 'content_views', ['viewer_id'], unique=False)
    op.create_table('email_verification_otps',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_otps_email'), 'email_verification_otps', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_otps_is_deleted'), 'email_verification_otps', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_email_verification_otps_is_used'), 'email_verification_otps', ['is_used'], unique=False)
    op.create_index(op.f('ix_email_verification_otps_otp_code'), 'email_verification_otps', ['otp_code'], unique=False)
    op.create_index(op.f('ix_email_verification_otps_user_id'), 'email_verification_otps', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_email'), 'email_verification_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_is_deleted'), 'email_verification_tokens', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_is_used'), 'email_verification_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('monetization_activity',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monetization_activity_action'), 'monetization_activity', ['action'], unique=False)
    op.create_index(op.f('ix_monetization_activity_campaign_id'), 'monetization_activity', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_monetization_activity_is_deleted'), 'monetization_activity', ['is_deleted'], unique=False)
    op.create_table('movie_files',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('quality_level', sa.String(length=10), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('container_format', sa.String(length=20), nullable=True),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('storage_region', sa.String(length=50), nullable=True),
    sa.Column('cdn_url', sa.String(length=500), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('subtitle_tracks', sa.Text(), nullable=True),
    sa.Column('audio_tracks', sa.Text(), nullable=True),
    sa.Column('available_languages', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'quality_level', name='unique_movie_quality')
    )
    op.create_index(op.f('ix_movie_files_content_id'), 'movie_files', ['content_id'], unique=False)
    op.create_index(op.f('ix_movie_files_is_deleted'), 'movie_files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_movie_files_is_ready'), 'movie_files', ['is_ready'], unique=False)
    op.create_table('password_reset_otps',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_otps_email'), 'password_reset_otps', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_is_deleted'), 'password_reset_otps', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_is_used'), 'password_reset_otps', ['is_used'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_otp_code'), 'password_reset_otps', ['otp_code'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_user_id'), 'password_reset_otps', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_is_deleted'), 'password_reset_tokens', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_is_used'), 'password_reset_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_family', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('parent_token_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_is_deleted'), 'refresh_tokens', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_family'), 'refresh_tokens', ['token_family'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('seasons',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('average_episode_duration', sa.Float(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'season_number', name='unique_content_season')
    )
    op.create_index(op.f('ix_seasons_air_date'), 'seasons', ['air_date'], unique=False)
    op.create_index(op.f('ix_seasons_content_id'), 'seasons', ['content_id'], unique=False)
    op.create_index(op.f('ix_seasons_is_deleted'), 'seasons', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_seasons_season_number'), 'seasons', ['season_number'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('billing_cycle_anchor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan'), 'subscriptions', ['plan'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_is_deleted'), 'token_blacklist', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_family', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_is_deleted'), 'tokens', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=False)
    op.create_index(op.f('ix_tokens_token_family'), 'tokens', ['token_family'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('profile_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_kids_profile', sa.Boolean(), nullable=False),
    sa.Column('age_rating_limit', sa.Integer(), nullable=False),
    sa.Column('language_preference', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('subtitle_preference', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('parental_controls_enabled', sa.Boolean(), nullable=False),
    sa.Column('content_restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('viewing_time_limit', sa.Integer(), nullable=True),
    sa.Column('bedtime_start', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('bedtime_end', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_is_deleted'), 'user_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_search_history',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_search_history_is_deleted'), 'user_search_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_search_history_last_searched_at'), 'user_search_history', ['last_searched_at'], unique=False)
    op.create_index(op.f('ix_user_search_history_search_query'), 'user_search_history', ['search_query'], unique=False)
    op.create_index(op.f('ix_user_search_history_user_id'), 'user_search_history', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('date_format', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('autoplay', sa.Boolean(), nullable=False),
    sa.Column('quality_preference', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('subtitle_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('audio_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_emails', sa.Boolean(), nullable=False),
    sa.Column('security_alerts', sa.Boolean(), nullable=False),
    sa.Column('billing_notifications', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('data_sharing', sa.Boolean(), nullable=False),
    sa.Column('analytics_tracking', sa.Boolean(), nullable=False),
    sa.Column('personalized_recommendations', sa.Boolean(), nullable=False),
    sa.Column('parental_controls_enabled', sa.Boolean(), nullable=False),
    sa.Column('content_rating_limit', sa.Integer(), nullable=False),
    sa.Column('viewing_time_limit', sa.Integer(), nullable=True),
    sa.Column('bedtime_start', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('bedtime_end', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('login_notifications', sa.Boolean(), nullable=False),
    sa.Column('session_timeout', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_is_deleted'), 'user_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('episodes',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tag_line', sa.Text(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('video_file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('container_format', sa.String(length=20), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('storage_region', sa.String(length=50), nullable=True),
    sa.Column('cdn_url', sa.String(length=500), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('subtitle_tracks', sa.Text(), nullable=True),
    sa.Column('audio_tracks', sa.Text(), nullable=True),
    sa.Column('available_languages', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('average_completion_rate', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'season_id', 'episode_number', name='unique_season_episode'),
    sa.UniqueConstraint('content_id', 'slug', name='unique_content_episode_slug')
    )
    op.create_index(op.f('ix_episodes_air_date'), 'episodes', ['air_date'], unique=False)
    op.create_index(op.f('ix_episodes_content_id'), 'episodes', ['content_id'], unique=False)
    op.create_index(op.f('ix_episodes_episode_number'), 'episodes', ['episode_number'], unique=False)
    op.create_index(op.f('ix_episodes_is_available'), 'episodes', ['is_available'], unique=False)
    op.create_index(op.f('ix_episodes_is_deleted'), 'episodes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_episodes_processing_status'), 'episodes', ['processing_status'], unique=False)
    op.create_index(op.f('ix_episodes_season_id'), 'episodes', ['season_id'], unique=False)
    op.create_index(op.f('ix_episodes_slug'), 'episodes', ['slug'], unique=False)
    op.create_index(op.f('ix_episodes_views_count'), 'episodes', ['views_count'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('receipt_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_payments_status'), 'subscription_payments', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_payments_stripe_invoice_id'), 'subscription_payments', ['stripe_invoice_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_stripe_payment_intent_id'), 'subscription_payments', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_subscription_id'), 'subscription_payments', ['subscription_id'], unique=False)
    op.create_table('user_content_interactions',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', 'interaction_type', name='unique_user_content_interaction')
    )
    op.create_index(op.f('ix_user_content_interactions_content_id'), 'user_content_interactions', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_content_interactions_interaction_type'), 'user_content_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_user_content_interactions_is_deleted'), 'user_content_interactions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_content_interactions_profile_id'), 'user_content_interactions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_content_interactions_user_id'), 'user_content_interactions', ['user_id'], unique=False)
    op.create_table('episode_qualities',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('quality_level', sa.String(length=10), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('cdn_url', sa.String(length=500), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'quality_level', name='unique_episode_quality')
    )
    op.create_index(op.f('ix_episode_qualities_episode_id'), 'episode_qualities', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_qualities_is_deleted'), 'episode_qualities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_episode_qualities_is_ready'), 'episode_qualities', ['is_ready'], unique=False)
    op.create_table('episode_views',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=True),
    sa.Column('quality_watched', sa.String(length=10), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('is_binge_watch', sa.Boolean(), nullable=False),
    sa.Column('came_from_episode_id', sa.UUID(), nullable=True),
    sa.Column('subtitle_language', sa.String(length=10), nullable=True),
    sa.Column('audio_language', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['came_from_episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_views_episode_id'), 'episode_views', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_views_is_deleted'), 'episode_views', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_episode_views_session_id'), 'episode_views', ['session_id'], unique=False)
    op.create_index(op.f('ix_episode_views_viewer_id'), 'episode_views', ['viewer_id'], unique=False)
    op.create_table('user_watch_history',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('current_episode_id', sa.UUID(), nullable=True),
    sa.Column('current_position_seconds', sa.Integer(), nullable=False),
    sa.Column('total_episodes_watched', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_currently_watching', sa.Boolean(), nullable=False),
    sa.Column('first_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_quality', sa.String(length=10), nullable=True),
    sa.Column('preferred_subtitle_language', sa.String(length=10), nullable=True),
    sa.Column('preferred_audio_language', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['current_episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='unique_user_content_history')
    )
    op.create_index(op.f('ix_user_watch_history_content_id'), 'user_watch_history', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_watch_history_is_deleted'), 'user_watch_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_watch_history_last_watched_at'), 'user_watch_history', ['last_watched_at'], unique=False)
    op.create_index(op.f('ix_user_watch_history_profile_id'), 'user_watch_history', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_watch_history_user_id'), 'user_watch_history', ['user_id'], unique=False)
    op.create_table('user_watch_progress',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('current_position_seconds', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('watch_percentage', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_watch_progress_content_id', 'user_watch_progress', ['content_id'], unique=False)
    op.create_index('idx_user_watch_progress_last_watched', 'user_watch_progress', ['last_watched_at'], unique=False)
    op.create_index('idx_user_watch_progress_user_content', 'user_watch_progress', ['user_id', 'content_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_episode', 'user_watch_progress', ['user_id', 'episode_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_id', 'user_watch_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_watch_progress_is_deleted'), 'user_watch_progress', ['is_deleted'], unique=False)
    op.create_table('watch_sessions',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('quality_setting', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_sessions_content_id'), 'watch_sessions', ['content_id'], unique=False)
    op.create_index(op.f('ix_watch_sessions_episode_id'), 'watch_sessions', ['episode_id'], unique=False)
    op.create_index(op.f('ix_watch_sessions_is_deleted'), 'watch_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_watch_sessions_session_id'), 'watch_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_watch_sessions_user_id'), 'watch_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_sessions_user_id'), table_name='watch_sessions')
    op.drop_index(op.f('ix_watch_sessions_session_id'), table_name='watch_sessions')
    op.drop_index(op.f('ix_watch_sessions_is_deleted'), table_name='watch_sessions')
    op.drop_index(op.f('ix_watch_sessions_episode_id'), table_name='watch_sessions')
    op.drop_index(op.f('ix_watch_sessions_content_id'), table_name='watch_sessions')
    op.drop_table('watch_sessions')
    op.drop_index(op.f('ix_user_watch_progress_is_deleted'), table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_id', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_episode', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_content', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_last_watched', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_content_id', table_name='user_watch_progress')
    op.drop_table('user_watch_progress')
    op.drop_index(op.f('ix_user_watch_history_user_id'), table_name='user_watch_history')
    op.drop_index(op.f('ix_user_watch_history_profile_id'), table_name='user_watch_history')
    op.drop_index(op.f('ix_user_watch_history_last_watched_at'), table_name='user_watch_history')
    op.drop_index(op.f('ix_user_watch_history_is_deleted'), table_name='user_watch_history')
    op.drop_index(op.f('ix_user_watch_history_content_id'), table_name='user_watch_history')
    op.drop_table('user_watch_history')
    op.drop_index(op.f('ix_episode_views_viewer_id'), table_name='episode_views')
    op.drop_index(op.f('ix_episode_views_session_id'), table_name='episode_views')
    op.drop_index(op.f('ix_episode_views_is_deleted'), table_name='episode_views')
    op.drop_index(op.f('ix_episode_views_episode_id'), table_name='episode_views')
    op.drop_table('episode_views')
    op.drop_index(op.f('ix_episode_qualities_is_ready'), table_name='episode_qualities')
    op.drop_index(op.f('ix_episode_qualities_is_deleted'), table_name='episode_qualities')
    op.drop_index(op.f('ix_episode_qualities_episode_id'), table_name='episode_qualities')
    op.drop_table('episode_qualities')
    op.drop_index(op.f('ix_user_content_interactions_user_id'), table_name='user_content_interactions')
    op.drop_index(op.f('ix_user_content_interactions_profile_id'), table_name='user_content_interactions')
    op.drop_index(op.f('ix_user_content_interactions_is_deleted'), table_name='user_content_interactions')
    op.drop_index(op.f('ix_user_content_interactions_interaction_type'), table_name='user_content_interactions')
    op.drop_index(op.f('ix_user_content_interactions_content_id'), table_name='user_content_interactions')
    op.drop_table('user_content_interactions')
    op.drop_index(op.f('ix_subscription_payments_subscription_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_stripe_payment_intent_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_stripe_invoice_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_status'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_episodes_views_count'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_slug'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_season_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_processing_status'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_is_deleted'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_is_available'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_episode_number'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_content_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_air_date'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_is_deleted'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_search_history_user_id'), table_name='user_search_history')
    op.drop_index(op.f('ix_user_search_history_search_query'), table_name='user_search_history')
    op.drop_index(op.f('ix_user_search_history_last_searched_at'), table_name='user_search_history')
    op.drop_index(op.f('ix_user_search_history_is_deleted'), table_name='user_search_history')
    op.drop_table('user_search_history')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_deleted'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_token_family'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_is_deleted'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_is_deleted'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_seasons_season_number'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_is_deleted'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_content_id'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_air_date'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_family'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_deleted'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_is_used'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_is_deleted'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_otps_user_id'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_otp_code'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_is_used'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_is_deleted'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_email'), table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    op.drop_index(op.f('ix_movie_files_is_ready'), table_name='movie_files')
    op.drop_index(op.f('ix_movie_files_is_deleted'), table_name='movie_files')
    op.drop_index(op.f('ix_movie_files_content_id'), table_name='movie_files')
    op.drop_table('movie_files')
    op.drop_index(op.f('ix_monetization_activity_is_deleted'), table_name='monetization_activity')
    op.drop_index(op.f('ix_monetization_activity_campaign_id'), table_name='monetization_activity')
    op.drop_index(op.f('ix_monetization_activity_action'), table_name='monetization_activity')
    op.drop_table('monetization_activity')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_is_used'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_is_deleted'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_email'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_otps_user_id'), table_name='email_verification_otps')
    op.drop_index(op.f('ix_email_verification_otps_otp_code'), table_name='email_verification_otps')
    op.drop_index(op.f('ix_email_verification_otps_is_used'), table_name='email_verification_otps')
    op.drop_index(op.f('ix_email_verification_otps_is_deleted'), table_name='email_verification_otps')
    op.drop_index(op.f('ix_email_verification_otps_email'), table_name='email_verification_otps')
    op.drop_table('email_verification_otps')
    op.drop_index(op.f('ix_content_views_viewer_id'), table_name='content_views')
    op.drop_index(op.f('ix_content_views_is_deleted'), table_name='content_views')
    op.drop_index(op.f('ix_content_views_content_id'), table_name='content_views')
    op.drop_table('content_views')
    op.drop_index(op.f('ix_content_reviews_user_id'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_status'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_is_deleted'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_content_id'), table_name='content_reviews')
    op.drop_table('content_reviews')
    op.drop_table('content_genres')
    op.drop_index(op.f('ix_content_crew_job_title'), table_name='content_crew')
    op.drop_table('content_crew')
    op.drop_index(op.f('ix_content_cast_job_title'), table_name='content_cast')
    op.drop_table('content_cast')
    op.drop_index(op.f('ix_ad_campaign_stats_stat_date'), table_name='ad_campaign_stats')
    op.drop_index(op.f('ix_ad_campaign_stats_is_deleted'), table_name='ad_campaign_stats')
    op.drop_index(op.f('ix_ad_campaign_stats_campaign_id'), table_name='ad_campaign_stats')
    op.drop_table('ad_campaign_stats')
    op.drop_index(op.f('ix_watch_history_user_id'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_last_watched_at'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_is_deleted'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_episode_id'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_content_id'), table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_index(op.f('ix_users_signup_type'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_profile_status'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stripe_webhook_events_stripe_event_id'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_processed'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_event_type'), table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    op.drop_index(op.f('ix_streaming_channels_name'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_language'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_is_deleted'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_country'), table_name='streaming_channels')
    op.drop_index(op.f('ix_streaming_channels_category'), table_name='streaming_channels')
    op.drop_table('streaming_channels')
    op.drop_index(op.f('ix_policies_title'), table_name='policies')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_slug'), table_name='policies')
    op.drop_index(op.f('ix_policies_reviewer_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_type'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_deleted'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_active'), table_name='policies')
    op.drop_index(op.f('ix_policies_author_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_people_slug'), table_name='people')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_index(op.f('ix_people_is_deleted'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_is_deleted'), table_name='genres')
    op.drop_index(op.f('ix_genres_is_active'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_faqs_is_deleted'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_contents_total_views'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_status'), table_name='contents')
    op.drop_index(op.f('ix_contents_slug'), table_name='contents')
    op.drop_index(op.f('ix_contents_reviews_count'), table_name='contents')
    op.drop_index(op.f('ix_contents_release_date'), table_name='contents')
    op.drop_index(op.f('ix_contents_platform_rating'), table_name='contents')
    op.drop_index(op.f('ix_contents_likes_count'), table_name='contents')
    op.drop_index(op.f('ix_contents_language'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_trending'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_premium'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_new_release'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_featured'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_deleted'), table_name='contents')
    op.drop_index(op.f('ix_contents_content_type'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_ad_campaigns_title'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_target_platform'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_status'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_is_deleted'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_ad_type'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    # ### end Alembic commands ###
