"""add_announcements_popups_tasks_tables

Revision ID: ba867e291173
Revises: c059e264fcf2
Create Date: 2025-10-29 05:58:30.160224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba867e291173'
down_revision = 'c059e264fcf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_webhook_events_event_type'), 'stripe_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_processed'), 'stripe_webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_stripe_event_id'), 'stripe_webhook_events', ['stripe_event_id'], unique=True)
    op.create_table('watch_history',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_history_content_id'), 'watch_history', ['content_id'], unique=False)
    op.create_index(op.f('ix_watch_history_episode_id'), 'watch_history', ['episode_id'], unique=False)
    op.create_index(op.f('ix_watch_history_is_deleted'), 'watch_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_watch_history_last_watched_at'), 'watch_history', ['last_watched_at'], unique=False)
    op.create_index(op.f('ix_watch_history_user_id'), 'watch_history', ['user_id'], unique=False)
    op.create_table('announcements',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_author_id'), 'announcements', ['author_id'], unique=False)
    op.create_index(op.f('ix_announcements_is_active'), 'announcements', ['is_active'], unique=False)
    op.create_index(op.f('ix_announcements_is_deleted'), 'announcements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_announcements_scheduled_date_time'), 'announcements', ['scheduled_date_time'], unique=False)
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    op.create_index(op.f('ix_announcements_title'), 'announcements', ['title'], unique=False)
    op.create_table('popups',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('popup_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popups_assignee_id'), 'popups', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_popups_due_date'), 'popups', ['due_date'], unique=False)
    op.create_index(op.f('ix_popups_is_active'), 'popups', ['is_active'], unique=False)
    op.create_index(op.f('ix_popups_is_deleted'), 'popups', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_popups_popup_name'), 'popups', ['popup_name'], unique=False)
    op.create_index(op.f('ix_popups_priority'), 'popups', ['priority'], unique=False)
    op.create_index(op.f('ix_popups_project'), 'popups', ['project'], unique=False)
    op.create_index(op.f('ix_popups_status'), 'popups', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('billing_cycle_anchor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan'), 'subscriptions', ['plan'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_tasks_is_active'), 'tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project'), 'tasks', ['project'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_title'), 'tasks', ['task_title'], unique=False)
    op.create_table('user_profiles',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('profile_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_kids_profile', sa.Boolean(), nullable=False),
    sa.Column('age_rating_limit', sa.Integer(), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('subtitle_preference', sa.String(length=10), nullable=False),
    sa.Column('parental_controls_enabled', sa.Boolean(), nullable=False),
    sa.Column('content_restrictions', sa.String(), nullable=True),
    sa.Column('viewing_time_limit', sa.Integer(), nullable=True),
    sa.Column('bedtime_start', sa.String(length=5), nullable=True),
    sa.Column('bedtime_end', sa.String(length=5), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_is_deleted'), 'user_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('autoplay', sa.Boolean(), nullable=False),
    sa.Column('quality_preference', sa.String(length=20), nullable=False),
    sa.Column('subtitle_language', sa.String(length=10), nullable=False),
    sa.Column('audio_language', sa.String(length=10), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_emails', sa.Boolean(), nullable=False),
    sa.Column('security_alerts', sa.Boolean(), nullable=False),
    sa.Column('billing_notifications', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.String(length=20), nullable=False),
    sa.Column('data_sharing', sa.Boolean(), nullable=False),
    sa.Column('analytics_tracking', sa.Boolean(), nullable=False),
    sa.Column('personalized_recommendations', sa.Boolean(), nullable=False),
    sa.Column('parental_controls_enabled', sa.Boolean(), nullable=False),
    sa.Column('content_rating_limit', sa.Integer(), nullable=False),
    sa.Column('viewing_time_limit', sa.Integer(), nullable=True),
    sa.Column('bedtime_start', sa.String(length=5), nullable=True),
    sa.Column('bedtime_end', sa.String(length=5), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('login_notifications', sa.Boolean(), nullable=False),
    sa.Column('session_timeout', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_is_deleted'), 'user_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('subscription_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_payments_status'), 'subscription_payments', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_payments_stripe_invoice_id'), 'subscription_payments', ['stripe_invoice_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_stripe_payment_intent_id'), 'subscription_payments', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_subscription_id'), 'subscription_payments', ['subscription_id'], unique=False)
    op.create_table('user_watch_progress',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('current_position_seconds', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('watch_percentage', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_watch_progress_content_id', 'user_watch_progress', ['content_id'], unique=False)
    op.create_index('idx_user_watch_progress_last_watched', 'user_watch_progress', ['last_watched_at'], unique=False)
    op.create_index('idx_user_watch_progress_user_content', 'user_watch_progress', ['user_id', 'content_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_episode', 'user_watch_progress', ['user_id', 'episode_id'], unique=False)
    op.create_index('idx_user_watch_progress_user_id', 'user_watch_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_watch_progress_is_deleted'), 'user_watch_progress', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_drm_keys_id'), table_name='drm_keys')
    op.drop_index(op.f('ix_drm_keys_video_id'), table_name='drm_keys')
    op.drop_table('drm_keys')
    op.drop_index(op.f('ix_active_streams_content_id'), table_name='active_streams')
    op.drop_index(op.f('ix_active_streams_id'), table_name='active_streams')
    op.drop_index(op.f('ix_active_streams_session_id'), table_name='active_streams')
    op.drop_index(op.f('ix_active_streams_user_id'), table_name='active_streams')
    op.drop_table('active_streams')
    op.drop_index(op.f('ix_license_requests_id'), table_name='license_requests')
    op.drop_index(op.f('ix_license_requests_session_id'), table_name='license_requests')
    op.drop_index(op.f('ix_license_requests_user_id'), table_name='license_requests')
    op.drop_index(op.f('ix_license_requests_video_id'), table_name='license_requests')
    op.drop_table('license_requests')
    op.add_column('user_content_interactions', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_content_interactions_profile_id'), 'user_content_interactions', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'user_content_interactions', 'user_profiles', ['profile_id'], ['id'])
    op.add_column('user_watch_history', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_watch_history_profile_id'), 'user_watch_history', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'user_watch_history', 'user_profiles', ['profile_id'], ['id'])
    op.add_column('users', sa.Column('analytics_data', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activity_log', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.String(), nullable=True))
    op.add_column('users', sa.Column('device_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_info')
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'activity_log')
    op.drop_column('users', 'analytics_data')
    op.drop_constraint(None, 'user_watch_history', type_='foreignkey')
    op.drop_index(op.f('ix_user_watch_history_profile_id'), table_name='user_watch_history')
    op.drop_column('user_watch_history', 'profile_id')
    op.drop_constraint(None, 'user_content_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_user_content_interactions_profile_id'), table_name='user_content_interactions')
    op.drop_column('user_content_interactions', 'profile_id')
    op.create_table('license_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('license_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('license_requests_pkey'))
    )
    op.create_index(op.f('ix_license_requests_video_id'), 'license_requests', ['video_id'], unique=False)
    op.create_index(op.f('ix_license_requests_user_id'), 'license_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_license_requests_session_id'), 'license_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_license_requests_id'), 'license_requests', ['id'], unique=False)
    op.create_table('active_streams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('active_streams_content_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('active_streams_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('active_streams_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('active_streams_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_active_streams_user_id'), 'active_streams', ['user_id'], unique=False)
    op.create_index(op.f('ix_active_streams_session_id'), 'active_streams', ['session_id'], unique=False)
    op.create_index(op.f('ix_active_streams_id'), 'active_streams', ['id'], unique=False)
    op.create_index(op.f('ix_active_streams_content_id'), 'active_streams', ['content_id'], unique=False)
    op.create_table('drm_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('key_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('drm_keys_pkey'))
    )
    op.create_index(op.f('ix_drm_keys_video_id'), 'drm_keys', ['video_id'], unique=True)
    op.create_index(op.f('ix_drm_keys_id'), 'drm_keys', ['id'], unique=False)
    op.drop_index(op.f('ix_user_watch_progress_is_deleted'), table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_id', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_episode', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_user_content', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_last_watched', table_name='user_watch_progress')
    op.drop_index('idx_user_watch_progress_content_id', table_name='user_watch_progress')
    op.drop_table('user_watch_progress')
    op.drop_index(op.f('ix_subscription_payments_subscription_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_stripe_payment_intent_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_stripe_invoice_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_status'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_is_deleted'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_deleted'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tasks_task_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_active'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_popups_status'), table_name='popups')
    op.drop_index(op.f('ix_popups_project'), table_name='popups')
    op.drop_index(op.f('ix_popups_priority'), table_name='popups')
    op.drop_index(op.f('ix_popups_popup_name'), table_name='popups')
    op.drop_index(op.f('ix_popups_is_deleted'), table_name='popups')
    op.drop_index(op.f('ix_popups_is_active'), table_name='popups')
    op.drop_index(op.f('ix_popups_due_date'), table_name='popups')
    op.drop_index(op.f('ix_popups_assignee_id'), table_name='popups')
    op.drop_table('popups')
    op.drop_index(op.f('ix_announcements_title'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_scheduled_date_time'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_deleted'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_active'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_author_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_watch_history_user_id'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_last_watched_at'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_is_deleted'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_episode_id'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_content_id'), table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_index(op.f('ix_stripe_webhook_events_stripe_event_id'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_processed'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_event_type'), table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    # ### end Alembic commands ###
