"""Add user settings and account management

Revision ID: c063cff3718d
Revises: e101b8cce52d
Create Date: 2025-10-24 12:02:37.417533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'c063cff3718d'
down_revision = 'e101b8cce52d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('date_format', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('autoplay', sa.Boolean(), nullable=False),
    sa.Column('quality_preference', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('subtitle_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('audio_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_emails', sa.Boolean(), nullable=False),
    sa.Column('security_alerts', sa.Boolean(), nullable=False),
    sa.Column('billing_notifications', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('data_sharing', sa.Boolean(), nullable=False),
    sa.Column('analytics_tracking', sa.Boolean(), nullable=False),
    sa.Column('personalized_recommendations', sa.Boolean(), nullable=False),
    sa.Column('parental_controls_enabled', sa.Boolean(), nullable=False),
    sa.Column('content_rating_limit', sa.Integer(), nullable=False),
    sa.Column('viewing_time_limit', sa.Integer(), nullable=True),
    sa.Column('bedtime_start', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('bedtime_end', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('login_notifications', sa.Boolean(), nullable=False),
    sa.Column('session_timeout', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_is_deleted'), 'user_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.drop_index(op.f('ix_stripe_webhook_events_event_type'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_processed'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_stripe_event_id'), table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    op.drop_index(op.f('ix_subscription_payments_status'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_stripe_invoice_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_stripe_payment_intent_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_subscription_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_subscriptions_plan'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('idx_user_content_interactions_profile_id'), table_name='user_content_interactions')
    op.create_index(op.f('ix_user_content_interactions_profile_id'), 'user_content_interactions', ['profile_id'], unique=False)
    op.drop_constraint(op.f('user_content_interactions_profile_id_fkey'), 'user_content_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'user_content_interactions', 'user_profiles', ['profile_id'], ['id'])
    op.alter_column('user_profiles', 'content_restrictions',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_user_profiles_is_kids'), table_name='user_profiles')
    op.drop_index(op.f('idx_user_profiles_is_primary'), table_name='user_profiles')
    op.drop_index(op.f('idx_user_profiles_profile_type'), table_name='user_profiles')
    op.drop_index(op.f('idx_user_profiles_user_id'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_is_deleted'), 'user_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_user_watch_history_profile_id'), table_name='user_watch_history')
    op.create_index(op.f('ix_user_watch_history_profile_id'), 'user_watch_history', ['profile_id'], unique=False)
    op.drop_constraint(op.f('user_watch_history_profile_id_fkey'), 'user_watch_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_watch_history', 'user_profiles', ['profile_id'], ['id'])
    op.add_column('user_watch_progress', sa.Column('profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user_watch_progress', 'user_profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_watch_progress', type_='foreignkey')
    op.drop_column('user_watch_progress', 'profile_id')
    op.drop_constraint(None, 'user_watch_history', type_='foreignkey')
    op.create_foreign_key(op.f('user_watch_history_profile_id_fkey'), 'user_watch_history', 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_watch_history_profile_id'), table_name='user_watch_history')
    op.create_index(op.f('idx_user_watch_history_profile_id'), 'user_watch_history', ['profile_id'], unique=False)
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_deleted'), table_name='user_profiles')
    op.create_index(op.f('idx_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_profiles_profile_type'), 'user_profiles', ['profile_type'], unique=False)
    op.create_index(op.f('idx_user_profiles_is_primary'), 'user_profiles', ['is_primary'], unique=False)
    op.create_index(op.f('idx_user_profiles_is_kids'), 'user_profiles', ['is_kids_profile'], unique=False)
    op.alter_column('user_profiles', 'last_used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_profiles', 'content_restrictions',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'user_content_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('user_content_interactions_profile_id_fkey'), 'user_content_interactions', 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_content_interactions_profile_id'), table_name='user_content_interactions')
    op.create_index(op.f('idx_user_content_interactions_profile_id'), 'user_content_interactions', ['profile_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plan', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('billing_cycle_anchor', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan'), 'subscriptions', ['plan'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('receipt_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('subscription_payments_subscription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_payments_pkey'))
    )
    op.create_index(op.f('ix_subscription_payments_subscription_id'), 'subscription_payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_stripe_payment_intent_id'), 'subscription_payments', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_stripe_invoice_id'), 'subscription_payments', ['stripe_invoice_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_status'), 'subscription_payments', ['status'], unique=False)
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_webhook_events_pkey'))
    )
    op.create_index(op.f('ix_stripe_webhook_events_stripe_event_id'), 'stripe_webhook_events', ['stripe_event_id'], unique=True)
    op.create_index(op.f('ix_stripe_webhook_events_processed'), 'stripe_webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_event_type'), 'stripe_webhook_events', ['event_type'], unique=False)
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_is_deleted'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
