"""Add streaming encryption fields

Revision ID: c600409f3e7c
Revises: dbd42bb8ab1c
Create Date: 2025-10-08 02:07:42.990747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c600409f3e7c'
down_revision = 'dbd42bb8ab1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_chunk_access',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_chunk_access_file_id'), 'streaming_chunk_access', ['file_id'], unique=False)
    op.create_index(op.f('ix_streaming_chunk_access_is_deleted'), 'streaming_chunk_access', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_streaming_chunk_access_user_id'), 'streaming_chunk_access', ['user_id'], unique=False)
    op.create_table('streaming_encryption_keys',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_encryption_keys_file_id'), 'streaming_encryption_keys', ['file_id'], unique=False)
    op.create_index(op.f('ix_streaming_encryption_keys_is_deleted'), 'streaming_encryption_keys', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_streaming_encryption_keys_key_id'), 'streaming_encryption_keys', ['key_id'], unique=True)
    op.create_table('streaming_encryption_tasks',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='streamingencryptionstatus'), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_encryption_tasks_file_id'), 'streaming_encryption_tasks', ['file_id'], unique=False)
    op.create_index(op.f('ix_streaming_encryption_tasks_is_deleted'), 'streaming_encryption_tasks', ['is_deleted'], unique=False)
    op.add_column('content_cast', sa.Column('job_title', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_content_cast_job_title'), 'content_cast', ['job_title'], unique=False)
    op.alter_column('content_crew', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_content_crew_job_title'), 'content_crew', ['job_title'], unique=False)
    op.add_column('episode_qualities', sa.Column('is_streaming_encrypted', sa.Boolean(), nullable=False))
    op.add_column('episode_qualities', sa.Column('streaming_encrypted_file_url', sa.String(length=500), nullable=True))
    op.add_column('episode_qualities', sa.Column('streaming_encryption_key_id', sa.String(length=100), nullable=True))
    op.add_column('episode_qualities', sa.Column('streaming_chunk_size', sa.Integer(), nullable=False))
    op.add_column('episode_qualities', sa.Column('streaming_total_chunks', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_episode_qualities_is_streaming_encrypted'), 'episode_qualities', ['is_streaming_encrypted'], unique=False)
    op.add_column('movie_files', sa.Column('is_streaming_encrypted', sa.Boolean(), nullable=False))
    op.add_column('movie_files', sa.Column('streaming_encrypted_file_url', sa.String(length=500), nullable=True))
    op.add_column('movie_files', sa.Column('streaming_encryption_key_id', sa.String(length=100), nullable=True))
    op.add_column('movie_files', sa.Column('streaming_chunk_size', sa.Integer(), nullable=False))
    op.add_column('movie_files', sa.Column('streaming_total_chunks', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_movie_files_is_streaming_encrypted'), 'movie_files', ['is_streaming_encrypted'], unique=False)
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_movie_files_is_streaming_encrypted'), table_name='movie_files')
    op.drop_column('movie_files', 'streaming_total_chunks')
    op.drop_column('movie_files', 'streaming_chunk_size')
    op.drop_column('movie_files', 'streaming_encryption_key_id')
    op.drop_column('movie_files', 'streaming_encrypted_file_url')
    op.drop_column('movie_files', 'is_streaming_encrypted')
    op.drop_index(op.f('ix_episode_qualities_is_streaming_encrypted'), table_name='episode_qualities')
    op.drop_column('episode_qualities', 'streaming_total_chunks')
    op.drop_column('episode_qualities', 'streaming_chunk_size')
    op.drop_column('episode_qualities', 'streaming_encryption_key_id')
    op.drop_column('episode_qualities', 'streaming_encrypted_file_url')
    op.drop_column('episode_qualities', 'is_streaming_encrypted')
    op.drop_index(op.f('ix_content_crew_job_title'), table_name='content_crew')
    op.alter_column('content_crew', 'job_title',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_content_cast_job_title'), table_name='content_cast')
    op.drop_column('content_cast', 'job_title')
    op.drop_index(op.f('ix_streaming_encryption_tasks_is_deleted'), table_name='streaming_encryption_tasks')
    op.drop_index(op.f('ix_streaming_encryption_tasks_file_id'), table_name='streaming_encryption_tasks')
    op.drop_table('streaming_encryption_tasks')
    op.drop_index(op.f('ix_streaming_encryption_keys_key_id'), table_name='streaming_encryption_keys')
    op.drop_index(op.f('ix_streaming_encryption_keys_is_deleted'), table_name='streaming_encryption_keys')
    op.drop_index(op.f('ix_streaming_encryption_keys_file_id'), table_name='streaming_encryption_keys')
    op.drop_table('streaming_encryption_keys')
    op.drop_index(op.f('ix_streaming_chunk_access_user_id'), table_name='streaming_chunk_access')
    op.drop_index(op.f('ix_streaming_chunk_access_is_deleted'), table_name='streaming_chunk_access')
    op.drop_index(op.f('ix_streaming_chunk_access_file_id'), table_name='streaming_chunk_access')
    op.drop_table('streaming_chunk_access')
    # ### end Alembic commands ###
