"""Movie Job title enum add in cast and crews

Revision ID: cce001799cb4
Revises: 6497e1a2b872
Create Date: 2025-09-23 02:36:18.515741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce001799cb4'
down_revision = '6497e1a2b872'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
