"""add_oauth_fields_to_user_model

Revision ID: dbd42bb8ab1c
Revises: 713b4303f20e
Create Date: 2025-09-27 01:18:31.214400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'dbd42bb8ab1c'
down_revision = '713b4303f20e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signup_type', sa.String(length=20), nullable=False, server_default='email'))
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('apple_id', sa.String(length=100), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_signup_type'), 'users', ['signup_type'], unique=False)
    # Remove server default after setting values
    op.alter_column('users', 'signup_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_signup_type'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'apple_id')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'signup_type')
    # ### end Alembic commands ###
