"""add_monetization_tables

Revision ID: dd332a9e41e5
Revises: 26a904270f97
Create Date: 2025-10-09 19:12:09.484714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd332a9e41e5'
down_revision = '26a904270f97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_campaigns',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_platform', sa.Enum('WEB', 'ANDROID', 'IOS', 'SMART_TV', 'OTHER', name='platformtype'), nullable=False),
    sa.Column('ad_type', sa.Enum('BANNER', 'VIDEO', 'NATIVE', 'INTERSTITIAL', 'OTHER', name='adtype'), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'DRAFT', name='campaignstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_ad_type'), 'ad_campaigns', ['ad_type'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_is_deleted'), 'ad_campaigns', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_status'), 'ad_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_target_platform'), 'ad_campaigns', ['target_platform'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_title'), 'ad_campaigns', ['title'], unique=False)
    op.create_table('ad_campaign_stats',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaign_stats_campaign_id'), 'ad_campaign_stats', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_campaign_stats_is_deleted'), 'ad_campaign_stats', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ad_campaign_stats_stat_date'), 'ad_campaign_stats', ['stat_date'], unique=False)
    op.create_table('monetization_activity',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monetization_activity_action'), 'monetization_activity', ['action'], unique=False)
    op.create_index(op.f('ix_monetization_activity_campaign_id'), 'monetization_activity', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_monetization_activity_is_deleted'), 'monetization_activity', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monetization_activity_is_deleted'), table_name='monetization_activity')
    op.drop_index(op.f('ix_monetization_activity_campaign_id'), table_name='monetization_activity')
    op.drop_index(op.f('ix_monetization_activity_action'), table_name='monetization_activity')
    op.drop_table('monetization_activity')
    op.drop_index(op.f('ix_ad_campaign_stats_stat_date'), table_name='ad_campaign_stats')
    op.drop_index(op.f('ix_ad_campaign_stats_is_deleted'), table_name='ad_campaign_stats')
    op.drop_index(op.f('ix_ad_campaign_stats_campaign_id'), table_name='ad_campaign_stats')
    op.drop_table('ad_campaign_stats')
    op.drop_index(op.f('ix_ad_campaigns_title'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_target_platform'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_status'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_is_deleted'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_ad_type'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    # ### end Alembic commands ###
