"""add_user_search_history_table

Revision ID: e625a428009b
Revises: dd332a9e41e5
Create Date: 2025-10-09 20:27:36.243070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e625a428009b'
down_revision = 'dd332a9e41e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search_history',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_search_history_is_deleted'), 'user_search_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_search_history_last_searched_at'), 'user_search_history', ['last_searched_at'], unique=False)
    op.create_index(op.f('ix_user_search_history_search_query'), 'user_search_history', ['search_query'], unique=False)
    op.create_index(op.f('ix_user_search_history_user_id'), 'user_search_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_search_history_user_id'), table_name='user_search_history')
    op.drop_index(op.f('ix_user_search_history_search_query'), table_name='user_search_history')
    op.drop_index(op.f('ix_user_search_history_last_searched_at'), table_name='user_search_history')
    op.drop_index(op.f('ix_user_search_history_is_deleted'), table_name='user_search_history')
    op.drop_table('user_search_history')
    # ### end Alembic commands ###
