"""Add email verification OTP table

Revision ID: e98c8e2f9736
Revises: 77afbce47b46
Create Date: 2025-09-17 04:34:00.954821

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e98c8e2f9736"
down_revision = "77afbce47b46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_otps",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("otp_code", sa.String(length=6), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_verification_otps_email"),
        "email_verification_otps",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_otps_is_deleted"),
        "email_verification_otps",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_otps_is_used"),
        "email_verification_otps",
        ["is_used"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_otps_otp_code"),
        "email_verification_otps",
        ["otp_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_otps_user_id"),
        "email_verification_otps",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_email_verification_otps_user_id"), table_name="email_verification_otps"
    )
    op.drop_index(
        op.f("ix_email_verification_otps_otp_code"),
        table_name="email_verification_otps",
    )
    op.drop_index(
        op.f("ix_email_verification_otps_is_used"), table_name="email_verification_otps"
    )
    op.drop_index(
        op.f("ix_email_verification_otps_is_deleted"),
        table_name="email_verification_otps",
    )
    op.drop_index(
        op.f("ix_email_verification_otps_email"), table_name="email_verification_otps"
    )
    op.drop_table("email_verification_otps")
    # ### end Alembic commands ###
