# Generated by Django 5.2.5 on 2025-08-30 05:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file_url",
                    models.URLField(max_length=500, verbose_name="Video File URL"),
                ),
                (
                    "duration",
                    models.FloatField(
                        help_text="Duration in seconds",
                        verbose_name="Duration (seconds)",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Thumbnail URL",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Views Count"),
                ),
                (
                    "likes_count",
                    models.IntegerField(default=0, verbose_name="Likes Count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Resolution"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Format"
                    ),
                ),
                (
                    "s3_bucket",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="S3 Bucket"
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="S3 Key"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "db_table": "videos_video",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Viewed At"),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="videos.video",
                        verbose_name="Video",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Viewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video View",
                "verbose_name_plural": "Video Views",
                "db_table": "videos_video_view",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="videos.video",
                        verbose_name="Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Like",
                "verbose_name_plural": "Video Likes",
                "db_table": "videos_video_like",
                "ordering": ["-created_at"],
                "unique_together": {("video", "user")},
            },
        ),
    ]
